### ISSUE TITLE
Getting Operational error  no such table: core_document

### ISSUE THREAD

**Issue by sohamghoshmusigma** [sibtc/simple-file-upload#2]
Hi, I tried doing a clone and running this program, I get an error saying this:

Request Method: | GET
-- | --
http://127.0.0.1:8000/
1.11.3
OperationalError
no such table: core_document
/home/musigma/virtualenvpycharm35/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
/home/musigma/virtualenvpycharm35/bin/python
3.5.0
['/home/musigma/django_project/FileUploadPOC/simple-file-upload',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/home/musigma/virtualenvpycharm35/lib/python3.5/site-packages',  '/home/musigma/virtualenvpycharm35/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg',  '/home/musigma/virtualenvpycharm35/lib/python3.5/site-packages/pip-9.0.1-py3.5.egg']
Fri, 11 Aug 2017 18:24:56 +0000

There is a lot more to this page, please let me know if you can help me or if you need more clarifications to do so. Thank you.

**Comment by vitorfs** [comment]
Hi @sohamghoshmusigma 
Before running make sure you run the project's migrations:

```bash
python manage.py migrate
```

Then try to run it again. This way, Django will create the `core_document` table in your database.

I will add further description in the repository, as already mentioned by the issue #1 

I hope it helps!

**Comment by sohamghoshmusigma** [comment]
Hi @vitorfs 

It worked like a charm. thank you for explaining why the solution works also. I'm new to django, so that definitely helped.
